#!/usr/bin/env python3
"""Convert the five egg PNGs to TouchGFX 4.25 ARGB8888 C++ arrays."""

from pathlib import Path
import zlib

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "TouchGFX" / "assets" / "images"
OUTPUT_DIR = ROOT / "TouchGFX" / "generated" / "images" / "src"
COLORS = ("blue", "green", "purple", "red", "yellow")


def convert(name: str) -> None:
    source = ASSET_DIR / f"egg_{name}.png"
    target = OUTPUT_DIR / f"image_egg_{name}.cpp"
    image = Image.open(source).convert("RGBA")

    if image.size != (32, 32):
        raise ValueError(f"{source} must be 32x32, got {image.size}")

    # TouchGFX ARGB8888 is stored little-endian in the generated byte array:
    # blue, green, red, alpha for every pixel.
    data = bytearray()
    # getdata() works across the Pillow versions commonly bundled with
    # STM32/TouchGFX development environments.
    for red, green, blue, alpha in image.getdata():
        data.extend((blue, green, red, alpha))

    crc = zlib.crc32(data) & 0xFFFFFFFF
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")

    content = (
        f"// 4.25.0 0x{crc:08x} D2 AY R0 FARGB8888 U565 N0 SExtFlashSection\n"
        "// Generated locally from TouchGFX/assets/images. Please, do not edit!\n\n"
        "#include <touchgfx/hal/Config.hpp>\n\n"
        'LOCATION_PRAGMA("ExtFlashSection")\n'
        f'KEEP extern const unsigned char image_egg_{name}[] '
        'LOCATION_ATTRIBUTE("ExtFlashSection") = { // 32x32 ARGB8888 pixels.\n'
        + "\n".join(lines)
        + "\n};\n"
    )
    with target.open("w", encoding="utf-8", newline="\n") as output:
        output.write(content)
    print(f"Generated {target.relative_to(ROOT)} ({len(data)} bytes)")


if __name__ == "__main__":
    for color in COLORS:
        convert(color)
