#!/usr/bin/env python3
"""Create split-egg sprites and convert all egg PNGs to TouchGFX arrays."""

from pathlib import Path
import zlib

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "TouchGFX" / "assets" / "images"
OUTPUT_DIR = ROOT / "TouchGFX" / "generated" / "images" / "src"
COLORS = ("blue", "green", "purple", "red", "yellow")
FRAGMENTS = ("left", "right")

# X coordinate removed from each scanline to form a visible, jagged crack.
# Both fragments remain on a 32x32 transparent canvas so their origin is the
# same as the intact egg and the animation can separate them without a jump.
CRACK_X = (
    15, 15, 14, 16, 15, 17, 14, 16,
    15, 16, 13, 15, 17, 14, 16, 15,
    18, 16, 14, 17, 15, 13, 16, 14,
    17, 15, 16, 14, 15, 15, 16, 16,
)


def create_fragments(color: str) -> None:
    source = ASSET_DIR / f"egg_{color}.png"
    image = Image.open(source).convert("RGBA")

    if image.size != (32, 32):
        raise ValueError(f"{source} must be 32x32, got {image.size}")

    for fragment in FRAGMENTS:
        output = Image.new("RGBA", image.size, (0, 0, 0, 0))
        for y in range(image.height):
            split_x = CRACK_X[y]
            for x in range(image.width):
                keep = x < split_x if fragment == "left" else x > split_x
                if keep:
                    output.putpixel((x, y), image.getpixel((x, y)))

        target = ASSET_DIR / f"egg_{color}_broken_{fragment}.png"
        output.save(target, optimize=True)
        print(f"Generated {target.relative_to(ROOT)}")


def encode_asset(asset_name: str):
    source = ASSET_DIR / f"{asset_name}.png"
    image = Image.open(source).convert("RGBA")

    if image.size != (32, 32):
        raise ValueError(f"{source} must be 32x32, got {image.size}")

    # TouchGFX ARGB8888 is stored little-endian in the generated byte array:
    # blue, green, red, alpha for every pixel.
    data = bytearray()
    # getdata() works across the Pillow versions commonly bundled with
    # STM32/TouchGFX development environments.
    for red, green, blue, alpha in image.getdata():
        data.extend((blue, green, red, alpha))

    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")

    definition = (
        'LOCATION_PRAGMA("ExtFlashSection")\n'
        f'KEEP extern const unsigned char image_{asset_name}[] '
        'LOCATION_ATTRIBUTE("ExtFlashSection") = { // 32x32 ARGB8888 pixels.\n'
        + "\n".join(lines)
        + "\n};"
    )
    return bytes(data), definition


def convert_color_bundle(color: str) -> None:
    asset_names = [f"egg_{color}"] + [
        f"egg_{color}_broken_{fragment}" for fragment in FRAGMENTS
    ]
    encoded = [encode_asset(asset_name) for asset_name in asset_names]
    crc = zlib.crc32(b"".join(data for data, _ in encoded)) & 0xFFFFFFFF
    target = OUTPUT_DIR / f"image_egg_{color}.cpp"
    content = (
        f"// 4.25.0 0x{crc:08x} D2 AY R0 FARGB8888 U565 N0 SExtFlashSection\n"
        "// Generated locally from TouchGFX/assets/images. Please, do not edit!\n\n"
        "#include <touchgfx/hal/Config.hpp>\n\n"
        + "\n\n".join(definition for _, definition in encoded)
        + "\n"
    )
    with target.open("w", encoding="utf-8", newline="\n") as output:
        output.write(content)
    print(f"Generated {target.relative_to(ROOT)} ({sum(len(data) for data, _ in encoded)} bytes)")


if __name__ == "__main__":
    for color in COLORS:
        create_fragments(color)
        convert_color_bundle(color)
